exclude: [Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
paginate: 5
markdown: kramdown
highlighter: rouge
github_username: colbywhite
kramdown:
  input: GFM
  hard_wrap: false
